opt_in_rules:
  - private_action
  - private_outlet
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - empty_string

excluded:
  - Pods
  - UIImagePickerController-Sample/AppDelegate.swift
  - UIImagePickerController-SampleTests
  - UIImagePickerController-SampleUITests
  
